Prefer open source team to Arkadia ecosystem
EmbarkStudios/opensource pull request #46
Opened 2022-04-07 10:25 UTC by bnjbvr

### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

Prefer open source team to Arkadia ecosystem, and update reference to internal Slack channel to one channel that's still active and not archived.

2022-04-07 10:32 UTC, repi approved these changes

2022-04-11 08:58 UTC, bnjbvr commented
Gentle ping @vojd please :)

2022-04-11 09:05 UTC, vojd requested changes

2022-04-11 09:05 UTC, vojd commented on content/maintenance-guidelines.md
> +If you are unable to find a suitable person, contact the Open-Source
`Open-Source` or `open-source` as per line [117](https://github.com/EmbarkStudios/opensource/pull/46/files#diff-f360081a29b5d57b3522683a4013126035d2fe0f0260121b372d0b14ef418abbR117)?

2022-04-11 09:38 UTC, vojd approved these changes

2022-04-11 09:42 UTC, merged